version: '2'
services:
  php:
    container_name: sm_api_php
    build:
      context: .
    volumes:
      - ./:/srv/app/
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - ${DOCKER_COMPOSE_HTTP_PORT}:80

  mysql:
    image: mysql:5.7.24
    container_name: sm_mysql
    environment:
      MYSQL_DATABASE: sm
      MYSQL_USER: sm
      MYSQL_PASSWORD: sm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_OUTER_PORT}:3306

volumes:
  mysql-data:
